version: '3.8'

services:
  nfenergylogger:
    image: ghcr.io/yanorei32/nf-energy-logger:latest@sha256:e2671e7ce2918d76a6c3465b2d9cdabf8df657fdeb6beabeedb472fbcabb1f0c
    hostname: nfenergylogger
    container_name: nfenergylogger__nfenergylogger
    restart: unless-stopped

    environment:
      NF_HOST: 192.168.179.2
      INFL_HOST: https://influxdb.yr32.net
      INFL_TOKEN: ${INFL_TOKEN}
      INFL_ORG: default
      INFL_BUCKET: power

    command: /usr/bin/nf-energy-logger run

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: nfenergylogger__default
