version: '3.8'

services:
  nfenergylogger:
    image: ghcr.io/yanorei32/nf-energy-logger:latest@sha256:1c2d260993725b0877b4325f34b1e80540de7d824fb5affcf232c1dd4a045df1
    hostname: nfenergylogger
    container_name: nfenergylogger__nfenergylogger
    restart: unless-stopped

    environment:
      NF_HOST: 192.168.179.2
      INFL_HOST: https://influxdb.yr32.net
      INFL_TOKEN: ${INFL_TOKEN}
      INFL_ORG: default
      INFL_BUCKET: power

    command: /usr/bin/nf-energy-logger run

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: nfenergylogger__default
