version: '3.8'

services:
  nfenergylogger:
    image: ghcr.io/yanorei32/nf-energy-logger:latest@sha256:524e790172a9d38867d3cc5178a3de948eaeecac7c03f89285c62fa1df97a1d5
    hostname: nfenergylogger
    container_name: nfenergylogger__nfenergylogger
    restart: unless-stopped

    environment:
      NF_HOST: 192.168.179.2
      INFL_HOST: https://influxdb.yr32.net
      INFL_TOKEN: ${INFL_TOKEN}
      INFL_ORG: default
      INFL_BUCKET: power

    command: /usr/bin/nf-energy-logger run

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: nfenergylogger__default
